SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION;

SELECT * FROM bank_account 
WHERE account_id = 1

WAITFOR DELAT '00:00:10'

SELECT * FROM bank_account 
WHERE account_id =1


ROLLBACK TRANSACTION;
